### ISSUE TITLE
Test fails if output file environment variable LOG_TIMELINE_JSON_LINES is defined

### ISSUE THREAD

**Issue by JJ** [jnthn/p6-log-timeline#6]
![Captura de pantalla de 2020-01-20 10-49-48](https://user-images.githubusercontent.com/500/72716554-b1971300-3b72-11ea-8343-dc1f3cb494eb.png)
And the message is totally opposite to what it happens: `[Log::Timeline] # Failed test 'No output configured for Log::Timeline'
[Log::Timeline] # at t/has-output.t line 4
[Log::Timeline] # You failed 1 test of 1
`

**Comment by jnthn** [comment]
> the message is totally opposite to what it happens

The message says what was expected, as is standard for test descriptions.

Anyway, this looks like a purposeful effort to break things, rather than a real problem. I guess the test could scrub the environment at BEGIN time. Please send a PR if it's important enough to you, but for me this is a "doctor it hurts when I do that".

**Comment by JJ** [comment]
I just tried to install it from a shell where I had already defined the variable. PR upcoming.
